Update README.md
github-technology-partners/ghes-storage-partners pull request #3
Opened 2022-03-22 20:33 UTC by ricduong

Updated look and feel for the main page.

2022-03-22 20:34 UTC, ricduong commented
Can you double check my work and update to the page? @abirismyname

2022-03-23 19:06 UTC, abirismyname reviewed
You might want to mention how to request access to [test and submit storage compatibility](https://github.com/github-technology-partners/enterprise-storage-check) it’s self-reporting but they need access to that repo to run the test

2022-03-23 19:19 UTC, abirismyname requested changes
Add (private repo) after [test and submit storage compatibility](https://github.com/github-technology-partners/enterprise-storage-check)

2022-03-23 19:20 UTC, abirismyname approved these changes

2022-03-23 19:21 UTC, merged